# Setup

In [1]:
import sys
import os
import pandas as pd
from IPython.display import display

# set path
project_root = os.path.abspath('')
while not os.path.isdir(os.path.join(project_root, 'utilities')):
    parent_dir = os.path.dirname(project_root)
    project_root = parent_dir

if project_root not in sys.path:
    sys.path.insert(0, project_root)
print(f"Project root set to: {project_root}")

# import testing modules
from utilities.hypothesis_testing.main import main as run_pipeline

Project root set to: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests

# Load data

In [2]:
dataset_filename = "wiki_clickstream_nl.csv" 

run_ks = True
run_bivariate = True
run_independence = False
graph_types_to_test = ['SmallWorld', 'StochasticBlock','ScaleFree']

base_dataset_name = dataset_filename.split('.')[0]
data_dir = os.path.join(project_root, 'data', 'real_world', 'preprocessed')
input_path = os.path.join(data_dir, dataset_filename)

# Run tests

In [3]:
for g_type in graph_types_to_test:

    print(f"STARTING TEST FOR: {g_type.upper()} CLASSIFICATION")

    output_dir = os.path.join(project_root, 'results', 'real_world') 
    batch_id = base_dataset_name
    dataset_id = g_type
    
    os.makedirs(output_dir, exist_ok=True)
    

    run_pipeline(
        input_path=input_path,
        dataset_id=dataset_id,
        batch_id=batch_id,
        output_dir=output_dir,
        run_ks=run_ks,
        run_independence=run_independence,
        run_bivariate=run_bivariate,
        jobs=-1,
        graph_type=g_type,
        data_type='real',
        auto_tune=True
    )
    report_csv_path = os.path.join(output_dir, batch_id, "summary_report.csv")
    
    if os.path.exists(report_csv_path):
            df_report = pd.read_csv(report_csv_path)
            current_report = df_report[df_report['Dataset ID'] == g_type]
            display(current_report)

STARTING TEST FOR: SMALLWORLD CLASSIFICATION
Starting EFHT analysis - Batch ID: wiki_clickstream_nl, Dataset ID: SmallWorld
Results for the current dataset will be saved in: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl/SmallWorld
The summary report will be saved in: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl

--- 2. Loading and preprocessing data for selected tests ---
   - Standardizing graph data (ensuring u < v and flip signed flows)...
   - Computing Graph Metrics for SmallWorld...
Metrics calculated.
   - Running KS Data Preprocessing...

   === Threshold Tuning for [KS] ===
   [Auto Iteration 1/10] | fraction_top: 0.50, fraction_bottom: 0.25
Auto-tuning balancing.
   [Auto Iteration 2/10] | fraction_top: 0.60, fraction_bottom: 0.20
Auto-tuning balancing.
   [Auto Iteration 3/10] | fraction_top: 0.70, fraction_bottom: 0.15
Auto-tuning balancing.
   Balance Reached (diff < 40%). Counts: 13670 vs 12365
   - Running Bivariate Data Preprocessing...

   === Threshold Tuning for [BEDT] ===
   [Auto Iteration 1/10] | fraction_top: 0.50, fraction_bottom: 0.25
Auto-tuning balancing.
   Balance Reached (diff < 40%). Counts: 4654 vs 5787

>>> Starting statistical tests <<<

--- 1. Running K-S Test ---

 ============ Running KS Test ============
# of Edges in Class1 : 13670
# of Edges in Class2 : 12365

KS Test Result:
KS_statistic D = 0.7135
P value = 0.0000e+00
Conclusion: Reject the null hypothesis (p < 0.016666666666666666), distributions are different.

--- 3. Running Bivariate Equivalence Test ---

 ============ Running Bivariate Test ============
# of Edge Pairs in Class1 : 4654
# of Edge Pairs in Class2 : 5787
Optimal K: 68
Observed KL = 8.4838

KL Under Null (Parallel):  20%|█▉        | 196/1000 [01:57<08:31,  1.57it/s]/Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/.conda/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
KL Under Null (Parallel): 100%|██████████| 1000/1000 [16:01<00:00,  1.04it/s]

Bivariate Test Result:
Observed Symmetric KL Divergence: 8.4838
P value: 0.0010
Conclusion: Reject the null hypothesis (p < 0.016666666666666666). The distributions are significantly different.
Appended results to: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl/summary_report.csv

==================================================
Analysis pipeline finished!

,Dataset ID,Test Name,Parameters,P-Value,Alpha,Conclusion,Fraction Top,Fraction Bottom
4,SmallWorld,KS Test,NaN,0.000000,0.016667,Reject H0,NaN,NaN
5,SmallWorld,Bivariate Equivalence Test,"K=39, #class1=1558, #class2=5977",0.000999,0.016667,Reject H0,NaN,NaN
6,SmallWorld,KS Test,NaN,0.000000,0.016667,Reject H0,0.5,0.25
7,SmallWorld,Bivariate Equivalence Test,"K=68, #class1=4654, #class2=5787",0.000999,0.016667,Reject H0,0.5,0.25
8,SmallWorld,KS Test,NaN,0.000000,0.016667,Reject H0,0.7,0.15
9,SmallWorld,Bivariate Equivalence Test,"K=68, #class1=4654, #class2=5787",0.000999,0.016667,Reject H0,0.5,0.25

STARTING TEST FOR: STOCHASTICBLOCK CLASSIFICATION
Starting EFHT analysis - Batch ID: wiki_clickstream_nl, Dataset ID: StochasticBlock
Results for the current dataset will be saved in: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl/StochasticBlock
The summary report will be saved in: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl

--- 2. Loading and preprocessing data for selected tests ---
   - Standardizing graph data (ensuring u < v and flip signed flows)...
   - Computing Graph Metrics for StochasticBlock...
   [Metrics computed: Sum of Degrees]
   - Running KS Data Preprocessing...

   === Threshold Tuning for [KS] ===
   [Auto Iteration 1/10] | fraction_top: 0.50, fraction_bottom: 0.20
Auto-tuning balancing.
   [Auto Iteration 2/10] | fraction_top: 0.60, fraction_bottom: 0.15
Auto-tuning balancing.
   [Auto Iteration 3/10] | fraction_top: 0.70, fraction_bottom: 0.10
Auto-tuning balancing.
   [Auto Iteration 4/10] | fraction_top: 0.80, fraction_bottom: 0.05
Auto-tuning balancing.
   Balance Reached (diff < 40%). Counts: 22083 vs 18767
   - Running Bivariate Data Preprocessing...

   === Threshold Tuning for [BEDT] ===
   [Auto Iteration 1/10] | fraction_top: 0.50, fraction_bottom: 0.20
Auto-tuning balancing.
   [Auto Iteration 2/10] | fraction_top: 0.60, fraction_bottom: 0.15
Auto-tuning balancing.
   [Auto Iteration 3/10] | fraction_top: 0.70, fraction_bottom: 0.10
Auto-tuning balancing.
   [Auto Iteration 4/10] | fraction_top: 0.65, fraction_bottom: 0.20
Auto-tuning balancing.
   [Auto Iteration 5/10] | fraction_top: 0.75, fraction_bottom: 0.15
Auto-tuning balancing.
   Balance Reached (diff < 40%). Counts: 11798 vs 11995

>>> Starting statistical tests <<<

--- 1. Running K-S Test ---

 ============ Running KS Test ============
# of Edges in Class1 : 22083
# of Edges in Class2 : 18767

KS Test Result:
KS_statistic D = 0.6971
P value = 0.0000e+00
Conclusion: Reject the null hypothesis (p < 0.016666666666666666), distributions are different.

--- 3. Running Bivariate Equivalence Test ---

 ============ Running Bivariate Test ============
# of Edge Pairs in Class1 : 11798
# of Edge Pairs in Class2 : 11995
Optimal K: 108
Observed KL = 9.0284

KL Under Null (Parallel): 100%|██████████| 1000/1000 [20:49<00:00,  1.25s/it]

Bivariate Test Result:
Observed Symmetric KL Divergence: 9.0284
P value: 0.0010
Conclusion: Reject the null hypothesis (p < 0.016666666666666666). The distributions are significantly different.
Appended results to: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl/summary_report.csv

==================================================
Analysis pipeline finished!

,Dataset ID,Test Name,Parameters,P-Value,Alpha,Conclusion,Fraction Top,Fraction Bottom
0,StochasticBlock,KS Test,NaN,0.000000,0.016667,Reject H0,NaN,NaN
1,StochasticBlock,Bivariate Equivalence Test,"K=38, #class1=1452, #class2=15920",0.000999,0.016667,Reject H0,NaN,NaN
10,StochasticBlock,KS Test,NaN,0.000000,0.016667,Reject H0,0.80,0.05
11,StochasticBlock,Bivariate Equivalence Test,"K=108, #class1=11798, #class2=11995",0.000999,0.016667,Reject H0,0.75,0.15

STARTING TEST FOR: SCALEFREE CLASSIFICATION
Starting EFHT analysis - Batch ID: wiki_clickstream_nl, Dataset ID: ScaleFree
Results for the current dataset will be saved in: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl/ScaleFree
The summary report will be saved in: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl

--- 2. Loading and preprocessing data for selected tests ---
   - Standardizing graph data (ensuring u < v and flip signed flows)...
   - Computing Graph Metrics for ScaleFree...
Metrics calculated (AFRC).
   - Running KS Data Preprocessing...

   === Threshold Tuning for [KS] ===
   [Auto Iteration 1/10] | fraction_top: 0.05, fraction_bottom: 0.70
Auto-tuning balancing.
   Balance Reached (diff < 40%). Counts: 16082 vs 15901
   - Running Bivariate Data Preprocessing...

   === Threshold Tuning for [BEDT] ===
   [Auto Iteration 1/10] | fraction_top: 0.05, fraction_bottom: 0.70
Auto-tuning balancing.
   [Auto Iteration 2/10] | fraction_top: 0.15, fraction_bottom: 0.65
Auto-tuning balancing.
   Balance Reached (diff < 40%). Counts: 12045 vs 9580

>>> Starting statistical tests <<<

--- 1. Running K-S Test ---

 ============ Running KS Test ============
# of Edges in Class1 : 16082
# of Edges in Class2 : 15901

KS Test Result:
KS_statistic D = 0.7189
P value = 0.0000e+00
Conclusion: Reject the null hypothesis (p < 0.016666666666666666), distributions are different.

--- 3. Running Bivariate Equivalence Test ---

 ============ Running Bivariate Test ============
# of Edge Pairs in Class1 : 12045
# of Edge Pairs in Class2 : 9580
Optimal K: 97
Observed KL = 8.7426

KL Under Null (Parallel):  97%|█████████▋| 966/1000 [15:28<00:32,  1.03it/s]/Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/.conda/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
KL Under Null (Parallel): 100%|██████████| 1000/1000 [15:55<00:00,  1.05it/s]

Bivariate Test Result:
Observed Symmetric KL Divergence: 8.7426
P value: 0.0010
Conclusion: Reject the null hypothesis (p < 0.016666666666666666). The distributions are significantly different.
Appended results to: /Users/jiaxin/Documents/Summer 2024/EFHT/Edge-Flow-Hypothesis-Tests/results/real_world/wiki_clickstream_nl/summary_report.csv

==================================================
Analysis pipeline finished!

,Dataset ID,Test Name,Parameters,P-Value,Alpha,Conclusion,Fraction Top,Fraction Bottom
2,ScaleFree,KS Test,NaN,0.000000,0.016667,Reject H0,NaN,NaN
3,ScaleFree,Bivariate Equivalence Test,"K=46, #class1=2207, #class2=11173",0.000999,0.016667,Reject H0,NaN,NaN
12,ScaleFree,KS Test,NaN,0.000000,0.016667,Reject H0,0.05,0.70
13,ScaleFree,Bivariate Equivalence Test,"K=97, #class1=12045, #class2=9580",0.000999,0.016667,Reject H0,0.15,0.65